module Countries
  def all
    {'Afghanistan'=>'af','Albania'=>'al','Algeria'=>'dz','American Samoa'=>'as','Andorra'=>'ad','Angola'=>'ao','Anguilla'=>'ai','Antarctica'=>'aq','Antigua and Barbuda'=>'ag','Argentina'=>'ar','Armenia'=>'am','Aruba'=>'aw','Australia'=>'au','Austria'=>'at','Azerbaijan'=>'az','Bahamas'=>'bs','Bahrain'=>'bh','Bangladesh'=>'bd','Barbados'=>'bb','Belarus'=>'by','Belgium'=>'be','Belize'=>'bz','Benin'=>'bj','Bermuda'=>'bm','Bhutan'=>'bt','Bolivia'=>'bo','Bosnia and Herzegovina'=>'ba','Botswana'=>'bw','Bouvet Island'=>'bv','Brazil'=>'br','British Indian Ocean Territory'=>'io','British Virgin Islands'=>'vg','Brunei'=>'bn','Bulgaria'=>'bg','Burkina Faso'=>'bf','Burundi'=>'bi','Cambodia'=>'kh','Cameroon'=>'cm','Canada'=>'ca','Cape Verde'=>'cv','Cayman Islands'=>'ky','Central African Republic'=>'cf','Chad'=>'td','Chile'=>'cl','China'=>'cn','Christmas Island'=>'cx','Cocos Islands'=>'cc','Colombia'=>'co','Comoros'=>'km','Congo'=>'cg','Cook Islands'=>'ck','Costa Rica'=>'cr','Croatia'=>'hr','Cuba'=>'cu','Cyprus'=>'cy','Czech Republic'=>'cz','Denmark'=>'dk','Djibouti'=>'dj','Dominica'=>'dm','Dominican Republic'=>'do','East Timor'=>'tp','Ecuador'=>'ec','Egypt'=>'eg','El Salvador'=>'sv','Equatorial Guinea'=>'gq','Eritrea'=>'er','Estonia'=>'ee','Ethiopia'=>'et','Falkland Islands'=>'fk','Faroe Islands'=>'fo','Fiji'=>'fj','Finland'=>'fi','France'=>'fr','French Guiana'=>'gf','French Polynesia'=>'pf','French Southern Territories'=>'tf','Gabon'=>'ga','Gambia'=>'gm','Georgia'=>'ge','Germany'=>'de','Ghana'=>'gh','Gibraltar'=>'gi','Greece'=>'gr','Greenland'=>'gl','Grenada'=>'gd','Guadeloupe'=>'gp','Guam'=>'gu','Guatemala'=>'gt','Guinea'=>'gn','Guinea-Bissau'=>'gw','Guyana'=>'gy','Haiti'=>'ht','Heard and McDonald Islands'=>'hm','Honduras'=>'hn','Hong Kong'=>'hk','Hungary'=>'hu','Iceland'=>'is','India'=>'in','Indonesia'=>'id','Iran'=>'ir','Iraq'=>'iq','Ireland'=>'ie','Israel'=>'il','Italy'=>'it','Ivory Coast'=>'ci','Jamaica'=>'jm','Japan'=>'jp','Jordan'=>'jo','Kazakhstan'=>'kz','Kenya'=>'ke','Kiribati'=>'ki','Korea, North'=>'kp','Korea, South'=>'kr','Kuwait'=>'kw','Kyrgyzstan'=>'kg','Laos'=>'la','Latvia'=>'lv','Lebanon'=>'lb','Lesotho'=>'ls','Liberia'=>'lr','Libya'=>'ly','Liechtenstein'=>'li','Lithuania'=>'lt','Luxembourg'=>'lu','Macau'=>'mo','Macedonia, Former Yugoslav Republic of'=>'mk','Madagascar'=>'mg','Malawi'=>'mw','Malaysia'=>'my','Maldives'=>'mv','Mali'=>'ml','Malta'=>'mt','Marshall Islands'=>'mh','Martinique'=>'mq','Mauritania'=>'mr','Mauritius'=>'mu','Mayotte'=>'yt','Mexico'=>'mx','Micronesia, Federated States of'=>'fm','Moldova'=>'md','Monaco'=>'mc','Mongolia'=>'mn','Montserrat'=>'ms','Morocco'=>'ma','Mozambique'=>'mz','Myanmar'=>'mm','Namibia'=>'na','Nauru'=>'nr','Nepal'=>'np','Netherlands'=>'nl','Netherlands Antilles'=>'an','New Caledonia'=>'nc','New Zealand'=>'nz','Nicaragua'=>'ni','Niger'=>'ne','Nigeria'=>'ng','Niue'=>'nu','Norfolk Island'=>'nf','Northern Mariana Islands'=>'mp','Norway'=>'no','Oman'=>'om','Pakistan'=>'pk','Palau'=>'pw','Panama'=>'pa','Papua New Guinea'=>'pg','Paraguay'=>'py','Peru'=>'pe','Philippines'=>'ph','Pitcairn Island'=>'pn','Poland'=>'pl','Portugal'=>'pt','Puerto Rico'=>'pr','Qatar'=>'qa','Reunion'=>'re','Romania'=>'ro','Russia'=>'ru','Rwanda'=>'rw','S. Georgia and S. Sandwich Isls.'=>'gs','Saint Kitts & Nevis'=>'kn','Saint Lucia'=>'lc','Saint Vincent and The Grenadines'=>'vc','Samoa'=>'ws','San Marino'=>'sm','Sao Tome and Principe'=>'st','Saudi Arabia'=>'sa','Senegal'=>'sn','Seychelles'=>'sc','Sierra Leone'=>'sl','Singapore'=>'sg','Slovakia'=>'sk','Slovenia'=>'si','Somalia'=>'so','South Africa'=>'za','Spain'=>'es','Sri Lanka'=>'lk','St. Helena'=>'sh','St. Pierre and Miquelon'=>'pm','Sudan'=>'sd','Suriname'=>'sr','Svalbard and Jan Mayen Islands'=>'sj','Swaziland'=>'sz','Sweden'=>'se','Switzerland'=>'ch','Syria'=>'sy','Taiwan'=>'tw','Tajikistan'=>'tj','Tanzania'=>'tz','Thailand'=>'th','Togo'=>'tg','Tokelau'=>'tk','Tonga'=>'to','Trinidad and Tobago'=>'tt','Tunisia'=>'tn','Turkey'=>'tr','Turkmenistan'=>'tm','Turks and Caicos Islands'=>'tc','Tuvalu'=>'tv','U.S. Minor Outlying Islands'=>'um','Uganda'=>'ug','Ukraine'=>'ua','United Arab Emirates'=>'ae','United Kingdom'=>'uk','United States of America'=>'us','Uruguay'=>'uy','Uzbekistan'=>'uz','Vanuatu'=>'vu','Vatican City'=>'va','Venezuela'=>'ve','Vietnam'=>'vn','Virgin Islands'=>'vi','Wallis and Futuna Islands'=>'wf','Western Sahara'=>'eh','Yemen'=>'ye','Yugoslavia (Former)'=>'yu','Zaire'=>'zr','Zambia'=>'zm','Zimbabwe'=>'zw'}
  end

  def all_in_array
    [['Afghanistan', 'af'],
    ['Albania', 'al'],
    ['Algeria', 'dz'],
    ['American Samoa', 'as'],
    ['Andorra', 'ad'],
    ['Angola', 'ao'],
    ['Anguilla', 'ai'],
    ['Antarctica', 'aq'],
    ['Antigua and Barbuda', 'ag'],
    ['Argentina', 'ar'],
    ['Armenia', 'am'],
    ['Aruba', 'aw'],
    ['Australia', 'au'],
    ['Austria', 'at'],
    ['Azerbaijan', 'az'],
    ['Bahamas', 'bs'],
    ['Bahrain', 'bh'],
    ['Bangladesh', 'bd'],
    ['Barbados', 'bb'],
    ['Belarus', 'by'],
    ['Belgium', 'be'],
    ['Belize', 'bz'],
    ['Benin', 'bj'],
    ['Bermuda', 'bm'],
    ['Bhutan', 'bt'],
    ['Bolivia', 'bo'],
    ['Bosnia and Herzegovina', 'ba'],
    ['Botswana', 'bw'],
    ['Bouvet Island', 'bv'],
    ['Brazil', 'br'],
    ['British Indian Ocean Territory', 'io'],
    ['British Virgin Islands', 'vg'],
    ['Brunei', 'bn'],
    ['Bulgaria', 'bg'],
    ['Burkina Faso', 'bf'],
    ['Burundi', 'bi'],
    ['Cambodia', 'kh'],
    ['Cameroon', 'cm'],
    ['Canada', 'ca'],
    ['Cape Verde', 'cv'],
    ['Cayman Islands', 'ky'],
    ['Central African Republic', 'cf'],
    ['Chad', 'td'],
    ['Chile', 'cl'],
    ['China', 'cn'],
    ['Christmas Island', 'cx'],
    ['Cocos Islands', 'cc'],
    ['Colombia', 'co'],
    ['Comoros', 'km'],
    ['Congo', 'cg'],
    ['Cook Islands', 'ck'],
    ['Costa Rica', 'cr'],
    ['Croatia', 'hr'],
    ['Cuba', 'cu'],
    ['Cyprus', 'cy'],
    ['Czech Republic', 'cz'],
    ['Denmark', 'dk'],
    ['Djibouti', 'dj'],
    ['Dominica', 'dm'],
    ['Dominican Republic', 'do'],
    ['East Timor', 'tp'],
    ['Ecuador', 'ec'],
    ['Egypt', 'eg'],
    ['El Salvador', 'sv'],
    ['Equatorial Guinea', 'gq'],
    ['Eritrea', 'er'],
    ['Estonia', 'ee'],
    ['Ethiopia', 'et'],
    ['Falkland Islands', 'fk'],
    ['Faroe Islands', 'fo'],
    ['Fiji', 'fj'],
    ['Finland', 'fi'],
    ['France', 'fr'],
    ['French Guiana', 'gf'],
    ['French Polynesia', 'pf'],
    ['French Southern Territories', 'tf'],
    ['Gabon', 'ga'],
    ['Gambia', 'gm'],
    ['Georgia', 'ge'],
    ['Germany', 'de'],
    ['Ghana', 'gh'],
    ['Gibraltar', 'gi'],
    ['Greece', 'gr'],
    ['Greenland', 'gl'],
    ['Grenada', 'gd'],
    ['Guadeloupe', 'gp'],
    ['Guam', 'gu'],
    ['Guatemala', 'gt'],
    ['Guinea', 'gn'],
    ['Guinea-Bissau', 'gw'],
    ['Guyana', 'gy'],
    ['Haiti', 'ht'],
    ['Heard and McDonald Islands', 'hm'],
    ['Honduras', 'hn'],
    ['Hong Kong', 'hk'],
    ['Hungary', 'hu'],
    ['Iceland', 'is'],
    ['India', 'in'],
    ['Indonesia', 'id'],
    ['Iran', 'ir'],
    ['Iraq', 'iq'],
    ['Ireland', 'ie'],
    ['Israel', 'il'],
    ['Italy', 'it'],
    ['Ivory Coast', 'ci'],
    ['Jamaica', 'jm'],
    ['Japan', 'jp'],
    ['Jordan', 'jo'],
    ['Kazakhstan', 'kz'],
    ['Kenya', 'ke'],
    ['Kiribati', 'ki'],
    ['Korea, North', 'kp'],
    ['Korea, South', 'kr'],
    ['Kuwait', 'kw'],
    ['Kyrgyzstan', 'kg'],
    ['Laos', 'la'],
    ['Latvia', 'lv'],
    ['Lebanon', 'lb'],
    ['Lesotho', 'ls'],
    ['Liberia', 'lr'],
    ['Libya', 'ly'],
    ['Liechtenstein', 'li'],
    ['Lithuania', 'lt'],
    ['Luxembourg', 'lu'],
    ['Macau', 'mo'],
    ['Macedonia, Former Yugoslav Republic of', 'mk'],
    ['Madagascar', 'mg'],
    ['Malawi', 'mw'],
    ['Malaysia', 'my'],
    ['Maldives', 'mv'],
    ['Mali', 'ml'],
    ['Malta', 'mt'],
    ['Marshall Islands', 'mh'],
    ['Martinique', 'mq'],
    ['Mauritania', 'mr'],
    ['Mauritius', 'mu'],
    ['Mayotte', 'yt'],
    ['Mexico', 'mx'],
    ['Micronesia, Federated States of', 'fm'],
    ['Moldova', 'md'],
    ['Monaco', 'mc'],
    ['Mongolia', 'mn'],
    ['Montserrat', 'ms'],
    ['Morocco', 'ma'],
    ['Mozambique', 'mz'],
    ['Myanmar', 'mm'],
    ['Namibia', 'na'],
    ['Nauru', 'nr'],
    ['Nepal', 'np'],
    ['Netherlands', 'nl'],
    ['Netherlands Antilles', 'an'],
    ['New Caledonia', 'nc'],
    ['New Zealand', 'nz'],
    ['Nicaragua', 'ni'],
    ['Niger', 'ne'],
    ['Nigeria', 'ng'],
    ['Niue', 'nu'],
    ['Norfolk Island', 'nf'],
    ['Northern Mariana Islands', 'mp'],
    ['Norway', 'no'],
    ['Oman', 'om'],
    ['Pakistan', 'pk'],
    ['Palau', 'pw'],
    ['Panama', 'pa'],
    ['Papua New Guinea', 'pg'],
    ['Paraguay', 'py'],
    ['Peru', 'pe'],
    ['Philippines', 'ph'],
    ['Pitcairn Island', 'pn'],
    ['Poland', 'pl'],
    ['Portugal', 'pt'],
    ['Puerto Rico', 'pr'],
    ['Qatar', 'qa'],
    ['Reunion', 're'],
    ['Romania', 'ro'],
    ['Russia', 'ru'],
    ['Rwanda', 'rw'],
    ['S. Georgia and S. Sandwich Isls.', 'gs'],
    ['Saint Kitts & Nevis', 'kn'],
    ['Saint Lucia', 'lc'],
    ['Saint Vincent and The Grenadines', 'vc'],
    ['Samoa', 'ws'],
    ['San Marino', 'sm'],
    ['Sao Tome and Principe', 'st'],
    ['Saudi Arabia', 'sa'],
    ['Senegal', 'sn'],
    ['Seychelles', 'sc'],
    ['Sierra Leone', 'sl'],
    ['Singapore', 'sg'],
    ['Slovakia', 'sk'],
    ['Slovenia', 'si'],
    ['Somalia', 'so'],
    ['South Africa', 'za'],
    ['Spain', 'es'],
    ['Sri Lanka', 'lk'],
    ['St. Helena', 'sh'],
    ['St. Pierre and Miquelon', 'pm'],
    ['Sudan', 'sd'],
    ['Suriname', 'sr'],
    ['Svalbard and Jan Mayen Islands', 'sj'],
    ['Swaziland', 'sz'],
    ['Sweden', 'se'],
    ['Switzerland', 'ch'],
    ['Syria', 'sy'],
    ['Taiwan', 'tw'],
    ['Tajikistan', 'tj'],
    ['Tanzania', 'tz'],
    ['Thailand', 'th'],
    ['Togo', 'tg'],
    ['Tokelau', 'tk'],
    ['Tonga', 'to'],
    ['Trinidad and Tobago', 'tt'],
    ['Tunisia', 'tn'],
    ['Turkey', 'tr'],
    ['Turkmenistan', 'tm'],
    ['Turks and Caicos Islands', 'tc'],
    ['Tuvalu', 'tv'],
    ['U.S. Minor Outlying Islands', 'um'],
    ['Uganda', 'ug'],
    ['Ukraine', 'ua'],
    ['United Arab Emirates', 'ae'],
    ['United Kingdom', 'uk'],
    ['United States of America', 'us'],
    ['Uruguay', 'uy'],
    ['Uzbekistan', 'uz'],
    ['Vanuatu', 'vu'],
    ['Vatican City', 'va'],
    ['Venezuela', 've'],
    ['Vietnam', 'vn'],
    ['Virgin Islands', 'vi'],
    ['Wallis and Futuna Islands', 'wf'],
    ['Western Sahara', 'eh'],
    ['Yemen', 'ye'],
    ['Yugoslavia (Former)', 'yu'],
    ['Zaire', 'zr'],
    ['Zambia', 'zm'],
    ['Zimbabwe', 'zw']]
  end
end

# include Countries
# l = all.sort
# s = []
# l.each{|v,k| s << ["['#{v}', '#{k}']"] }
# puts "[" + s.join(",\n")+ "]"
